language: go

env:
  global:
  - GO111MODULE=on

matrix:
  include:
  - go: 1.8.x
  - go: 1.x
  - go: master

script:
- if [ "${TRAVIS_GO_VERSION}" = "1.x" ]; then make check; else make test; fi;
- make build

after_success:
- bash <(curl -s https://codecov.io/bash)
