name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Static analysis and testing
    strategy:
      matrix:
        go:
        - '1.15'
        - '1.14'
        - '1.13'
        - '1.12'
        - '1.11'
        os:
        - 'ubuntu-18.04'
        - 'macos-10.15'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Installing tools
      run: make tools

    - name: Static analysis and testing
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        make check

    - name: Codecov
      uses: codecov/codecov-action@v1

  ci-without-go-modules:
    name: Static analysis and testing without Go modules
    strategy:
      matrix:
        go:
        - '1.11'
        - '1.10'
        - '1.9'
        - '1.8'
        os:
        - 'ubuntu-18.04'
        - 'macos-10.15'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Static analysis and testing
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        go test ./... -count=10 -race

    - name: Codecov
      uses: codecov/codecov-action@v1
